version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=eduos-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - eduos-db
    volumes:
      - hf_cache:/root/.cache/huggingface

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  eduos-db:
    image: ankane/pgvector:v0.5.1
    container_name: eduos_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - eduos_postgres_data:/var/lib/postgresql/data

volumes:
  eduos_postgres_data:
  hf_cache: