"""Add schedule fields to Subject

Revision ID: 07145178d210
Revises: 7ac9ca69880b
Create Date: 2026-06-24 19:02:27.013373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07145178d210'
down_revision: Union[str, Sequence[str], None] = '7ac9ca69880b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE dayofweek AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')")
    op.execute("CREATE TYPE timeblock AS ENUM ('B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7')")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', name='dayofweek'), nullable=True))
    op.add_column('subjects', sa.Column('time_block', sa.Enum('B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', name='timeblock'), nullable=True))
    op.add_column('subjects', sa.Column('room', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'room')
    op.drop_column('subjects', 'time_block')
    op.drop_column('subjects', 'day_of_week')

    op.execute("DROP TYPE timeblock")
    op.execute("DROP TYPE dayofweek")
    # ### end Alembic commands ###
