"""Move Task to academic and create table

Revision ID: bc071085cd20
Revises: 07145178d210
Create Date: 2026-06-24 19:35:14.954809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc071085cd20'
down_revision: Union[str, Sequence[str], None] = '07145178d210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=sa.String(),
               nullable=True)
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               nullable=False)
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
