"""Add summary to AcademicFile

Revision ID: e90c541ce9c1
Revises: fe892835b6a2
Create Date: 2026-06-22 00:25:44.414707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90c541ce9c1'
down_revision: Union[str, Sequence[str], None] = 'fe892835b6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_files', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_files', 'summary')
    # ### end Alembic commands ###
